server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/horizonhub?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: xxxx@qq.com
    host: smtp.qq.com
    port: 465
    password: xxxx
    default-encoding: UTF-8
send:
  mail:
    open: false
